### ISSUE TITLE
[Question] Why run in a fiber ?

### ISSUE THREAD

**Issue by theodorDiaconu** [peerlibrary/meteor-control-mergebox#6]
https://github.com/peerlibrary/meteor-control-mergebox/blob/master/server.coffee#L65

Why do you run this in a separate fiber ?

I also looked here, but don't fully understand:
https://github.com/peerlibrary/node-fiber-utils/blob/master/src/server.coffee#L49

**Comment by theodorDiaconu** [comment]
I20171109-23:12:48.263(-5)? Exception in defer callback: Error: Removed nonexistent document twbR7cZNAJuxmL3v5
I20171109-23:12:48.264(-5)?     at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
I20171109-23:12:48.264(-5)?     at Session.removed (packages/ddp-server/livedata_server.js:394:10)

--- RedisOplog can run multiple removed(sameId) in the same Fiber. If you run them in the same fiber, the exception won't trigger. But disableMergebox, automatically runs it in a separate fiber.

**Comment by mitar** [comment]
No, the code you linked above does not make it run in separate fiber, but it makes it serialize code across fibers. It is like Java `synchronized` method. So it just defines a critical section no other fiber can jump in at the same time into it. This is necessary on the server (in contrast with client) because multiple fibers ("threads") can run at the same time.

So something else is happening here, I think.

**Comment by theodorDiaconu** [comment]
^ This answered my question.

**Comment by mitar** [comment]
Not sure why it breaks your code though.
